apiVersion: v1
kind: Service
metadata:
  labels:
    app: maventomcat
  name: maventomcat
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8096
      protocol: TCP
  selector:
    app: maventomcat
